spring.application.name=PRODUCT-SERVICE
server.port=8090
spring.data.mongodb.auto-index-creation=true
server.servlet.context-path=/product-service
# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://userrobin:rEaBu5jKxJVtVKGe@cluster01.ph2ecg2.mongodb.net/productdb?appName=Cluster01
server.compression.enabled=true
server.compression.mime-types=application/json,application/json;charset=UTF-8
server.compression.min-response-size=1024

