spring.application.name=PRODUCT-SERVICE
server.port=8090
server.servlet.context-path=/product-service
# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://userrobin:rEaBu5jKxJVtVKGe@cluster01.ph2ecg2.mongodb.net/productdb?appName=Cluster01

